# Generated by Django 4.1.2 on 2022-10-30 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='direction',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to=settings.AUTH_USER_MODEL, verbose_name='Curator'),
        ),
        migrations.AddField(
            model_name='direction',
            name='subjects',
            field=models.ManyToManyField(related_name='directions', to='faculty.subject', verbose_name='Subjects'),
        ),
    ]
